### ISSUE TITLE
오픈소스에 추가 문의드립니다.

### ISSUE THREAD

**Issue by ljlm0402** [SoYoung210/cra-template-soso#2]
안녕하세요.
현재 IT 기업에 3년차 재직중인 개발자입니다.

우선 좋은 블로그와 자료를 공유주신 점에 대하여 감사의 말씀부터드립니다.

본론으로, 현 개발자님의 코드에 대해 좋은 인상을 받아서 혹시 실례가 안된다면,
제 오픈소스에 추가하고 싶습니다.

제 오픈소스는 링크공유드립니다.
감사합니다.

link : [https://github.com/ljlm0402/tsghc](https://github.com/ljlm0402/tsghc)

**Comment by SoYoung210** [comment]
앗 이슈를 너무 늦게봤습니다. 🙏   네, 그렇게 해주시면 감사합니다..! @ljlm0402
